name: CICD

on:
  push:
    branches:
    - master
  pull_request:
    paths:
      - '**.go'

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci-lint:
    name: "lint"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.x]
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v5

  build:
    name: "build"
    runs-on: ubuntu-latest
    needs: [golangci-lint]
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'

    - name: Run testing
      run: go test -v

    - name: Run build
      run: go build -o tp-cesi main.go

    - name: Publish go binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: tp-cesi
        path: tp-cesi

    
  publish:
    name: "publish"
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    steps:
    - uses: actions/checkout@v2

    - name: Download go binary artifact
      uses: actions/download-artifact@v2
      with:
        name: tp-cesi
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Deploy to Docker registry
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Deploy to Docker registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: mbonnafon/tp-cesi:${{ github.head_ref || 'master' }}, mbonnafon/tp-cesi:${{ github.sha}}, 